#!/bin/sh

# Usage: extract-entitlements <input-file-path> [output-file-path]

function printError() {
    echo "$(tput bold)$(tput setaf 1)extract-entitlements:$(tput sgr0) "$1
}

# Validate arguments.
if [ "$#" -lt 1 ]; then
    printError "Invalid number of arguments.\n"
    echo "Usage: extract-entitlements <input-file-path> [output-file-path]"
    echo "\nThe output file path argument is optional. If missing, the file will be placed in the current working directory.\n"
    exit -1
fi

# The path to the IPA of interest.
IPA_DIRECTORY=$1

# Check if the IPA exists.
if [ ! -f $IPA_DIRECTORY ]; then
    printError "The \""$IPA_DIRECTORY"\" IPA could not be found."
    exit -1
fi

# The directory of where to output the entitlements file.
OUTPUT_DIRECTORY=$2

# Default to the current working directory if no output directory is provided.
if [ -z $OUTPUT_DIRECTORY ]; then
    OUTPUT_DIRECTORY="."
fi

# Validate that the output directory exists.
if [ ! -d $OUTPUT_DIRECTORY ]; then
    printError "The output directory \""$OUTPUT_DIRECTORY"\" could not be found."
    exit -1
fi

# Create a temporary working directory.
TEMPORARY_DIRECTORY=$(mktemp -d -t extract-entitlements-tmp)

# Unpackage the IPA into the temporary directory.
unzip -q $IPA_DIRECTORY -d $TEMPORARY_DIRECTORY

# Check for the Payload directory in the IPA.
if [ ! -d $TEMPORARY_DIRECTORY/Payload ]; then
    printError "The Payload directory is missing from the IPA archive."
    rm -r $TEMPORARY_DIRECTORY
    exit -1
fi

# Check for the *.app directory in the IPA.
if [ ! -d $TEMPORARY_DIRECTORY/Payload/*.app ]; then
    printError "The unpackaged IPA does not seem to contain a *.app. The contents are:"
    ls $TEMPORARY_DIRECTORY/Payload
    rm -r $TEMPORARY_DIRECTORY
    exit -1
fi

# Generate the entitlements file.
FULL_OUTPUT_PATH=$OUTPUT_DIRECTORY/$(date +%s)-generated-entitlements.plist
codesign -d --entitlements - $TEMPORARY_DIRECTORY/Payload/*.app > $FULL_OUTPUT_PATH

# Notify of success.
echo "$(tput bold)$(tput setaf 2)extract-entitlements:$(tput sgr0) Generated output file: "$FULL_OUTPUT_PATH

# Cleanup.
rm -r $TEMPORARY_DIRECTORY
